export const formRevision = 5;

export const schema = {
	title: 'Please fill your details below:',
	type: 'object',
	required: ['age', 'gender', 'country', 'status'],
	properties: {
		age: {
			type: 'integer',
			title: 'Age'
		},
		gender: {
			type: 'string',
			title: 'Gender',
			enum: [
				'Male',
				'Female',
				'Other',
			],
		},
		height: {
			type: ['null', 'object'],
			title: 'Height',
			properties: { unit: { type: ['string'] } },
		},
		country: {
			type: 'string',
			title: 'Country',
			enum: [
				`Afghanistan`,
				`Åland Islands`,
				`Albania`,
				`Algeria`,
				`American Samoa`,
				`Andorra`,
				`Angola`,
				`Anguilla`,
				`Antarctica`,
				`Antigua and Barbuda`,
				`Argentina`,
				`Armenia`,
				`Aruba`,
				`Australia`,
				`Austria`,
				`Azerbaijan`,
				`Bahamas`,
				`Bahrain`,
				`Bangladesh`,
				`Barbados`,
				`Belarus`,
				`Belgium`,
				`Belize`,
				`Benin`,
				`Bermuda`,
				`Bhutan`,
				`Bolivia`,
				`Bosnia and Herzegovina`,
				`Botswana`,
				`Bouvet Island`,
				`Brazil`,
				`British Indian Ocean Territory`,
				`Brunei Darussalam`,
				`Bulgaria`,
				`Burkina Faso`,
				`Burundi`,
				`Cambodia`,
				`Cameroon`,
				`Canada`,
				`Cape Verde`,
				`Cayman Islands`,
				`Central African Republic`,
				`Chad`,
				`Chile`,
				`China`,
				`Christmas Island`,
				`Cocos (Keeling) Islands`,
				`Colombia`,
				`Comoros`,
				`Congo`,
				`Congo, The Democratic Republic of The`,
				`Cook Islands`,
				`Costa Rica`,
				`Cote D'ivoire`,
				`Croatia`,
				`Cuba`,
				`Cyprus`,
				`Czech Republic`,
				`Denmark`,
				`Djibouti`,
				`Dominica`,
				`Dominican Republic`,
				`Ecuador`,
				`Egypt`,
				`El Salvador`,
				`Equatorial Guinea`,
				`Eritrea`,
				`Estonia`,
				`Ethiopia`,
				`Falkland Islands (Malvinas)`,
				`Faroe Islands`,
				`Fiji`,
				`Finland`,
				`France`,
				`French Guiana`,
				`French Polynesia`,
				`French Southern Territories`,
				`Gabon`,
				`Gambia`,
				`Georgia`,
				`Germany`,
				`Ghana`,
				`Gibraltar`,
				`Greece`,
				`Greenland`,
				`Grenada`,
				`Guadeloupe`,
				`Guam`,
				`Guatemala`,
				`Guernsey`,
				`Guinea`,
				`Guinea-bissau`,
				`Guyana`,
				`Haiti`,
				`Heard Island and Mcdonald Islands`,
				`Holy See (Vatican City State)`,
				`Honduras`,
				`Hong Kong`,
				`Hungary`,
				`Iceland`,
				`India`,
				`Indonesia`,
				`Iran, Islamic Republic of`,
				`Iraq`,
				`Ireland`,
				`Isle of Man`,
				`Israel`,
				`Italy`,
				`Jamaica`,
				`Japan`,
				`Jersey`,
				`Jordan`,
				`Kazakhstan`,
				`Kenya`,
				`Kiribati`,
				`Korea, Democratic People's Republic of`,
				`Korea, Republic of`,
				`Kuwait`,
				`Kyrgyzstan`,
				`Lao People's Democratic Republic`,
				`Latvia`,
				`Lebanon`,
				`Lesotho`,
				`Liberia`,
				`Libyan Arab Jamahiriya`,
				`Liechtenstein`,
				`Lithuania`,
				`Luxembourg`,
				`Macao`,
				`Macedonia, The Former Yugoslav Republic of`,
				`Madagascar`,
				`Malawi`,
				`Malaysia`,
				`Maldives`,
				`Mali`,
				`Malta`,
				`Marshall Islands`,
				`Martinique`,
				`Mauritania`,
				`Mauritius`,
				`Mayotte`,
				`Mexico`,
				`Micronesia, Federated States of`,
				`Moldova, Republic of`,
				`Monaco`,
				`Mongolia`,
				`Montenegro`,
				`Montserrat`,
				`Morocco`,
				`Mozambique`,
				`Myanmar`,
				`Namibia`,
				`Nauru`,
				`Nepal`,
				`Netherlands`,
				`Netherlands Antilles`,
				`New Caledonia`,
				`New Zealand`,
				`Nicaragua`,
				`Niger`,
				`Nigeria`,
				`Niue`,
				`Norfolk Island`,
				`Northern Mariana Islands`,
				`Norway`,
				`Oman`,
				`Pakistan`,
				`Palau`,
				`Palestinian Territory, Occupied`,
				`Panama`,
				`Papua New Guinea`,
				`Paraguay`,
				`Peru`,
				`Philippines`,
				`Pitcairn`,
				`Poland`,
				`Portugal`,
				`Puerto Rico`,
				`Qatar`,
				`Reunion`,
				`Romania`,
				`Russian Federation`,
				`Rwanda`,
				`Saint Helena`,
				`Saint Kitts and Nevis`,
				`Saint Lucia`,
				`Saint Pierre and Miquelon`,
				`Saint Vincent and The Grenadines`,
				`Samoa`,
				`San Marino`,
				`Sao Tome and Principe`,
				`Saudi Arabia`,
				`Senegal`,
				`Serbia`,
				`Seychelles`,
				`Sierra Leone`,
				`Singapore`,
				`Slovakia`,
				`Slovenia`,
				`Solomon Islands`,
				`Somalia`,
				`South Africa`,
				`South Georgia and The South Sandwich Islands`,
				`Spain`,
				`Sri Lanka`,
				`Sudan`,
				`Suriname`,
				`Svalbard and Jan Mayen`,
				`Swaziland`,
				`Sweden`,
				`Switzerland`,
				`Syrian Arab Republic`,
				`Taiwan (ROC)`,
				`Tajikistan`,
				`Tanzania, United Republic of`,
				`Thailand`,
				`Timor-leste`,
				`Togo`,
				`Tokelau`,
				`Tonga`,
				`Trinidad and Tobago`,
				`Tunisia`,
				`Turkey`,
				`Turkmenistan`,
				`Turks and Caicos Islands`,
				`Tuvalu`,
				`Uganda`,
				`Ukraine`,
				`United Arab Emirates`,
				`United Kingdom`,
				`United States`,
				`United States Minor Outlying Islands`,
				`Uruguay`,
				`Uzbekistan`,
				`Vanuatu`,
				`Venezuela`,
				`Viet Nam`,
				`Virgin Islands, British`,
				`Virgin Islands, U.S.`,
				`Wallis and Futuna`,
				`Western Sahara`,
				`Yemen`,
				`Zambia`,
				`Zimbabwe`,
			],
		},
		// address: { type: "string", title: "Address" },
		// city: { type: "string", title: "City" },
		// zipcode: { type: "string", title: "Zip code" },
		backgroundDiseases: {
			type: 'array',
			title: 'Have you been diagnosed with any of the following conditions?',
			items: {
				type: 'string',
				enum: [
					'Diabetes',
					'Hypertension',
					'Ischemic heart disease',
					'Asthma',
					'Allergies',
					'Chronic lung disease',
					'Chronic kidney disease',
					'Seasonal allergies',
				],
			},
			uniqueItems: true,
		},
		smokingHabits: {
			type: 'string',
			title: 'Do you smoke?',
			enum: [
				`I currently smoke`,
				`I used to smoke`,
				`I've never smoked`,
			],
		},
		status: {
			type: "string",
			title: "What is your current status?",
			enum: [
				'Not in isolation',
				'Hospitalized',
				'In isolation due to being diagnosed with COVID-19',
				'In isolation due to recent international travel',
				'In isolation due to contact with an individual who was infected with coronavirus or an individual who recently returned from any destination abroad',
				'In isolation due to government regulations',
			],
		},
		covid19: {
			type: 'object',
			title: '',
			required: ['diagnosedCovid19'],
			properties: {
				diagnosedCovid19: {
					type: 'string',
					title: "Were you diagnosed with COVID-19?",
					enum: ['No', 'Yes'],
				},
			},
			dependencies: {
				diagnosedCovid19: {
					oneOf: [
						{
							properties: {
								diagnosedCovid19: {
									enum: ['Yes'],
								},
								testSymptoms: {
									type: "array",
									title: "BEFORE being tested for COVID-19, have you experienced any of the following symptoms?",
									items: {
										type: 'string',
										enum: [
											'I feel well',
											'I have a fever',
											'Dry cough',
											'Cough with sputum production',
											'Fatigue',
											'Muscle aches',
											'Headache',
											'Sore throat',
											'Sneezing',
											'Shortness of breath',
											'Runny nose or nasal congestion',
											'Itching (eyes or other)',
											'Diarrhea',
											'Nausea and/or vomiting'
										],
									},
									uniqueItems: true,
								},
								testFever: { type: ['null', 'object'], title: 'Fever at test', properties: { unit: { type: 'string' } } },
								testDate: { type: 'string', format: 'date', title: 'When were you tested for COVID-19?' },
								currentSymptoms: {
									type: "array",
									title: "Are you currently experiencing any of the following symptoms?",
									items: {
										type: 'string',
										enum: [
											'I feel well',
											'I have a fever',
											'Dry cough',
											'Cough with sputum production',
											'Fatigue',
											'Muscle aches',
											'Headache',
											'Sore throat',
											'Sneezing',
											'Shortness of breath',
											'Runny nose or Nasal congestion',
											'Itching (eyes or other)',
											'Diarrhea',
											'Nausea and/or vomiting'
										],
									},
									uniqueItems: true,
								},
								currentFever: { type: ['null', 'object'], title: 'Current fever', properties: { unit: { type: 'string' } } },
							},
						},
						{
							properties: {
								diagnosedCovid19: {
									enum: ['No'],
								},
								currentSymptoms: {
									type: "array",
									title: "Are you currently experiencing any of the following symptoms:",
									items: {
										type: 'string',
										enum: [
											'I feel well',
											'I have a fever',
											'Dry cough',
											'Cough with sputum production',
											'Fatigue',
											'Muscle aches',
											'Headache',
											'Sore throat',
											'Sneezing',
											'Shortness of breath',
											'Runny nose or Nasal congestion',
											'Itching (eyes or other)',
											'Diarrhea',
											'Nausea and/or vomiting'
										],
									},
									uniqueItems: true,
								},
								currentFever: { type: ['null', 'object'], title: 'Current body temperature', properties: { unit: { type: 'string' } } },
							},
						},
					]
				},
			},
		},
	},
} as any;

export const uiSchema = {
	height: {
		'ui:field': 'height',
	},
	backgroundDiseases: {
		'ui:widget': 'checkboxes',
	},
	covid19: {
		testSymptoms: {
			'ui:widget': 'checkboxes',
		},
		testFever: {
			'ui:field': 'degrees',
		},
		currentSymptoms: {
			'ui:widget': 'checkboxes',
		},
		currentFever: {
			'ui:field': 'degrees',
		},
	},
} as any;

export type Task = { title: any, description?: string };
export const tasksList: Array<[string, Task]> = [
	['cough', { title: 'Please cough three times' }],
	['count', { title: 'Count from 1 to 20' }],
	['alphabet', { title: `Please recite the alphabet:`, description: `A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z` }],
	['eeee', { title: 'Say the vowel "ee" for as long as you can: EEEE', description: '(as in the word "cheese")'  }],
	['oooo', { title: 'Say the vowel "o" for as long as you can: OOOO', description: '(as in the word "box")' }],
	['aaaa', { title: 'Say the vowel "a" for as long as you can: AAAA', description: '(as in the word "sad")' }],
];
